/**
 * Callnet's first string catalog.
 *
 * Keeping copy behind stable keys makes the call experience localization-ready
 * without adding a translation runtime to the critical calling path yet.
 */
export const strings = {
  call: {
    screenTitle: 'Call',
    appName: 'Callnet',
    closeScreen: 'Close call screen',
    endAndClose: 'End and close call',
    noPersonSelected: 'No person selected',
    chooseSomeone: 'Choose someone before starting a call.',
    back: 'Back',
    done: 'Done',
    states: {
      ready: 'Ready to call',
      outgoing: 'Calling…',
      incoming: 'Incoming call',
      ringing: 'Ringing…',
      connecting: 'Connecting…',
      connected: 'Connected',
      ending: 'Ending call…',
      failed: 'Call failed',
      ended: 'Call ended',
    },
    alreadyCalling: (name: string) => `You are already calling ${name}.`,
    failures: {
      peerBusy: 'That person is already on another call.',
      permissionDenied: 'Microphone or camera permission was denied.',
      permissionHint: 'Allow access in device settings, then try the call again.',
      authenticated: 'The authenticated call could not connect.',
      demo: 'The demo call could not connect.',
    },
    diagnostics: (value: string) => `Diagnostic: ${value}`,
    video: {
      developmentClientRequired: 'Video preview requires the WebRTC development client.',
      waiting: 'Waiting for video…',
      connecting: 'Connecting video…',
      localPreview: 'Your video preview',
    },
    actions: {
      voiceCall: 'Voice call',
      videoCall: 'Video call',
      accept: 'Accept call',
      reject: 'Reject',
      cancel: 'Cancel',
      cancelCall: 'Cancel call',
      simulateTimeout: 'Simulate timeout',
      end: 'End call',
      openSettings: 'Open Settings',
      openSettingsHint: "Opens Callnet's device permissions",
    },
    controls: {
      mute: 'Mute',
      unmute: 'Unmute',
      microphone: 'Mute microphone',
      unmuteMicrophone: 'Unmute microphone',
      speaker: 'Speaker',
      earpiece: 'Earpiece',
      useSpeaker: 'Use speaker',
      useEarpiece: 'Use earpiece',
      camera: 'Camera',
      cameraOff: 'Camera off',
      turnCameraOff: 'Turn camera off',
      turnCameraOn: 'Turn camera on',
      flip: 'Flip',
      switchCamera: 'Switch camera',
      toggleControls: 'Show or hide call controls',
    },
  },
  incoming: {
    screenTitle: 'Incoming Call',
    unavailableTitle: 'No incoming call',
    unavailableCopy: 'This call is no longer available.',
    label: (callType: string) => `INCOMING ${callType.toUpperCase()} CALL`,
    callingNow: 'Calling you now',
    answer: (callType: string) => `Answer ${callType.toLowerCase()} call`,
    decline: 'Decline',
  },
  home: {
    screenTitle: 'Calls',
    profile: 'Open profile',
    introTitle: 'Private calls, made simple.',
    introCopy: 'Connect with someone you know in one focused flow.',
    recent: 'Recent calls',
    empty: 'Your recent calls will appear here.',
    emptyHint: 'Use the button below to start your first call.',
    startCall: 'Start a call',
    privateByDesign: 'PRIVATE BY DESIGN',
    privacyCopy: 'Your call history stays on this device.',
    demoMode: 'LOCAL DEMO MODE',
    demoCopy: 'Exercise an incoming call flow without another device.',
    tryIncoming: 'Try incoming call',
    authenticated: 'AUTHENTICATED WEBRTC',
    statuses: {
      connected: 'CONNECTED',
      connecting: 'CONNECTING…',
      offline: 'OFFLINE',
    },
    statusCopy: {
      connected: 'Ready for secure calls with your Firebase identity.',
      connecting: 'Connecting to the calling service.',
      offline: 'The calling service is unavailable. Check your connection.',
    },
    diagnostic: (value: string) => `Diagnostic: ${value}`,
    retry: 'Retry connection',
    dateToday: 'Today',
    dateYesterday: 'Yesterday',
    time: (value: string) => value,
    callTypes: { voice: 'Voice', video: 'Video' },
    callStatuses: {
      completed: 'Completed call',
      missed: 'Missed call',
      timedOut: 'Timed out call',
      rejected: 'Declined call',
      cancelled: 'Cancelled call',
      failed: 'Failed call',
      incoming: 'Incoming call',
      outgoing: 'Outgoing call',
    },
  },
  profile: {
    screenTitle: 'Profile',
    heading: 'Your profile',
    identityCopy: 'Your account identifies you securely across devices.',
    accountFallback: 'Callnet account',
    emailUnavailable: 'Email not available',
    usernameHint: 'Share your @username so people can find you securely.',
    privacyLabel: 'PRIVACY',
    privacyHeading: 'Clear, limited data handling',
    privacy: {
      media: 'Media',
      mediaCopy: 'Calls use WebRTC. Callnet does not record audio or video.',
      connections: 'Connections',
      connectionsCopy: 'Direct connections are preferred. TURN may relay encrypted media when needed.',
      history: 'Call history',
      historyCopy: 'Detailed recent-call history is kept locally on this device.',
      permissions: 'Permissions',
      permissionsCopy: 'Microphone and camera access are requested only when a call needs them.',
    },
    signOut: 'Sign out',
  },
  auth: {
    appName: 'Callnet',
    signInTitle: 'Welcome to Callnet',
    createTitle: 'Create your Callnet account',
    signInCopy: 'Private calls with the people you know, across your devices.',
    createCopy: 'Choose a simple identity so people can find you and call you.',
    google: 'Continue with Google',
    emailDivider: 'OR USE EMAIL',
    displayNameLabel: 'Display name',
    displayNamePlaceholder: 'How people will see you',
    usernameLabel: 'Callnet username',
    usernamePlaceholder: 'your.handle',
    usernameHint: '3–30 characters: letters, numbers, dots, dashes, or underscores.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholderCreate: 'At least 6 characters',
    passwordPlaceholderSignIn: 'Your password',
    errorTitle: 'Couldn’t continue',
    signIn: 'Sign in',
    createAccount: 'Create account',
    switchToCreate: 'Create a new account',
    switchToSignIn: 'I already have an account',
    privateByDesign: 'PRIVATE BY DESIGN',
    privacyCopy: 'No recordings. No public profile directory. Just focused calls.',
    errors: {
      emailPassword: 'Enter your email and password.',
      displayName: 'Enter a display name.',
      username: 'Choose a username with 3–30 letters, numbers, dots, dashes, or underscores.',
    },
  },
} as const;

export type AppStrings = typeof strings;
